apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-terraform
  annotations:
    github.com/project-slug: victor-ribamar-verzel/EC2-AWS
  description: AWS EKS cluster managed by Terraform
  tags:
    - aws
    - ec2
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: guests
