apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ec2-terraform
  annotations:
    github.com/project-slug: samgabrail/aws-eks
  description: AWS EKS cluster managed by Terraform
  tags:
    - aws
    - eks
    - terraform
spec:
  type: service
  lifecycle: experimental
  owner: guests
