name: EC2 on AWS

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Nome da sua instancia EC2'
        required: true
      region:
        description: 'AWS Region for the cluster'
        required: true
      image:
        description: 'Imagem base da sua Instancia'
        required: true
      instace_type:
        description: 'Imagem base da sua Instancia'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

jobs:
  apply:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}
    - name: Terraform Init
      run: terraform init
      working-directory: Terraform
    - name: Terraform Format
      run: terraform fmt
      working-directory: Terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform
    - name: Terraform Apply
      run: terraform apply -var instanceName=${{ github.event.inputs.instanceName }} -var region=${{ github.event.inputs.region }} -var image=${{ github.event.inputs.image}} -var instace_type=${{ github.event.inputs.instance_type}} -auto-approve
      working-directory: Terraform

  destroy:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region }}
    - name: Terraform Init
      run: terraform init
      working-directory: Terraform
    - name: Terraform FMT
      run: terraform fmt
      working-directory: Terraform
    - name: Terraform Validate
      run: terraform validate
      working-directory: Terraform
    - name: Terraform Destroy
      run: terraform destroy -var instanceName=${{ github.event.inputs.instanceName }} -var region=${{ github.event.inputs.region }} -auto-approve
      working-directory: Terraform